###################################
#### This script receives a RNA expression matrix generated by hybridation/scanning and an annotation table.
####    The program retrieves separated differential expression tables for each the possible comparisons in a tsv format
####    As well as a list (RData) with the same information 
####    RNA program in https://github.com/raulmejia/DSP-Oszwald
####      
####     Input description:
####        expression matrix: tab separated, rows = featrures, cols= sources/samples, there should not be colname over the first column(for the rownames); colnames shouldn't start with a number
####        annotdf: rows = cols from the expression matrix, also you should provide the name of column that contain your labels
####                Try to use character labels and if you have a "reference class" you can name it "Control" (case insensitive) the contrasts
####                against this category will be arranged properly and they will have priority
####     Output:
####        pdf, if your labels contain the word "Normal" (case insensitive) those graphs will be plotted first
####
####    Author of the script: Raúl Mejía
####
#### Example:
####      Rscript /PathA/Differential_expression_hybridized-n-scanned-Data-trough-limma.R /PathB/ExpMat_Demo.tsv /PathC/Annot_table_Demo.tsv /Path/code-this-repository/ /Path/yourResults/ label normal 0 0.05 5 Label_4_your_results
#### 
####    
###################################
#### 0) loading and/or installing required libraries
################################### 
if (!require("argparse")) {
  install.packages("argparse", ask =FALSE)
  library("argparse")
}
if (!require("gtools")) {
  install.packages("gtools", ask =FALSE)
  library("gtools")
}
if (!require("BiocManager")) {
  install.packages("BiocManager", ask =FALSE)
  library("BiocManager")
}
if (!require("limma")) {
  BiocManager::install("limma", ask =FALSE)
  library("limma")
}
if (!require("tidyverse")) {
  install.packages("tidyverse", ask =FALSE)
  library("tidyverse")
}
########################################
#### data given by the user
#########################################
myargs <- commandArgs(trailingOnly = TRUE)

# path_expression_matrix <- "" 
path_expression_matrix <- myargs[1]

# path_annotation_table <-""
path_annotation_table <- myargs[2]

# path_code <- ""
path_code <- myargs[3] 

# Label_for_yor_results <- ""
Label_for_yor_results <- myargs[4]

# column_of_labels_in_the_annotdf <- "Tissue" # name of the column in your annotation data frame that contains the labels
column_of_labels_in_the_annotdf <- myargs[5]

# my_reference_category <- "Kidney"
my_reference_category <- myargs[6]

# mylfc = 1
mylfc <- myargs[7]

# myp.value = 0.05
myp.value <- myargs[8]

# number_of_sets_4_the_VennDiagram <- 5
number_of_sets_4_the_VennDiagram <- myargs[9]

# Folder_to_save_results <- ""
Folder_to_save_results <- myargs[10]



############################
###### Basic Processing of data given by the user for example Paths
############################
path_code <- normalizePath( path_code )
path_2_load_myMakeContrasts <- paste0( path_code,"/","libraries/makeallContrasts.R" )
source( path_2_load_myMakeContrasts )

dir.create( Folder_to_save_results , recursive = TRUE)
Folder_to_save_results <- normalizePath(Folder_to_save_results)

############################
###### Body
#############################
# reading your matrices
myexpmat <- read.table( file= path_expression_matrix , sep="\t", header = TRUE, row.names = 1, check.names = FALSE)
annotdf <- read.table( file= path_annotation_table, sep="\t", header = TRUE, row.names = 1, check.names = FALSE)

if( length(which( colnames(myexpmat)  %in% rownames(annotdf) )) != length(colnames(myexpmat))  ){
  print("The number columns in your expmat is different than the rows in your Annotation Table")
  quit()
}
if( length(which( colnames(myexpmat)  %in% rownames(annotdf) )) != length( rownames(annotdf) )  ){
  print("The number columns in your expmat is different than the rows in your Annotation Table")
  quit()
}
   
# Desgin Matrix
designmat <- model.matrix( ~0+  as.factor( annotdf [,column_of_labels_in_the_annotdf]) )
    colnames(designmat) <- levels(as.factor( annotdf [,column_of_labels_in_the_annotdf] ))
   
# Fitting the lineal model    
myfit <- lmFit( myexpmat, designmat  ) # fitting the linear model

mycontMat <- mymakeContrasts(designmat , my_reference_category) # make your matrix of contrasts

myfit2 <- contrasts.fit( myfit, mycontMat)
myefit <- eBayes(myfit2) # moderate standard errors of the estimated log-fold changes

##################################################
### Creating the object to store the results
##################################################
list_TopTable_mylfc_n_pval <- list()
list_TopTable_mylfc_n_pval[[1]] <- topTable( myefit , coef=1, adjust="BH", p.value = myp.value, lfc = mylfc, number = Inf)
for(k in 2:dim(mycontMat)[2]){
  list_TopTable_mylfc_n_pval[[k]] <- topTable( myefit , coef=k, adjust="BH", p.value = myp.value, lfc = mylfc, number = Inf)
}
names(list_TopTable_mylfc_n_pval) <- colnames(mycontMat )

################################## 
## writing down the results
##################################
for( k in 1:length(list_TopTable_mylfc_n_pval) ){
  Name_of_theComparison <- str_replace_all( names(list_TopTable_mylfc_n_pval)[k], " ", "")
  path_file <- paste0(Folder_to_save_results,"/",Label_for_yor_results,"_Contrast...",Name_of_theComparison,".tsv")
    write.table( list_TopTable_mylfc_n_pval[[k]], file = path_file,  sep= "\t", quote=FALSE)
} # Saving all the DEG table with the cut parameters given by the user

path_RDS <-  paste0(Folder_to_save_results,"/",Label_for_yor_results,"_Contrast...all.rds")
saveRDS(list_TopTable_mylfc_n_pval, file=path_RDS)

##################################
###### Including a Venn Diagram
##################################
decidemyefit <-decideTests(myefit)

decidemyefit_2_plot <- decidemyefit[ , 1:number_of_sets_4_the_VennDiagram]

path_2pdf <-  paste0(Folder_to_save_results,"/",Label_for_yor_results,"_VenDiagram.pdf")
pdf(file=path_2pdf )
vennDiagram(decidemyefit_2_plot)
vennDiagram(decidemyefit_2_plot, 
            include=c("up", "down"),
            counts.col=c("red", "blue"),
            circle.col = c("red", "blue", "green3"))
dev.off()
